### ISSUE TITLE
bibxml9 xi:include for STDs doesn't provide info on RFCs with numbers less than 1000

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#250]
I tested the bibxml9 xi:include functionality with the following XML code:

    <xi:include href="https://bib.ietf.org/public/rfc/bibxml9/reference.STD.0003.xml"/>
    <xi:include href="https://bib.ietf.org/public/rfc/bibxml9/reference.STD.0005.xml"/>
    <xi:include href="https://bib.ietf.org/public/rfc/bibxml9/reference.STD.0008.xml"/>
    <xi:include href="https://bib.ietf.org/public/rfc/bibxml9/reference.STD.0010.xml"/>

It produces the following in the output files. Note that all entries labeled "[title unavailable]" are for RFCs that have numbers less than 1000. For instance, STD10 contains the following RFCs: 821, 974, 1869, and 1870. Only RFCs 1869 and 1870 are listed in the output. 

     [STD10]   "[title unavailable]".

               "[title unavailable]".

               Klensin, J., Freed, N., Rose, M., Stefferud, E., and D.
               Crocker, "SMTP Service Extensions", STD 10, RFC 1869,
               November 1995.

               Klensin, J., Freed, N., and K. Moore, "SMTP Service
               Extension for Message Size Declaration", STD 10, RFC 1870,
               November 1995.

               <https://www.rfc-editor.org/info/std10>

    [STD3]     Braden, R., Ed., "Requirements for Internet Hosts -
               Communication Layers", STD 3, RFC 1122, October 1989.

               Braden, R., Ed., "Requirements for Internet Hosts -
               Application and Support", STD 3, RFC 1123, October 1989.

               <https://www.rfc-editor.org/info/std3>

    [STD5]     "[title unavailable]".

               "[title unavailable]".

               "[title unavailable]".

               "[title unavailable]".

               "[title unavailable]".

               Deering, S E., "Host extensions for IP multicasting",
               STD 5, RFC 1112, August 1989.

               <https://www.rfc-editor.org/info/std5>

    [STD8]     "[title unavailable]".

               "[title unavailable]".

               <https://www.rfc-editor.org/info/std8>
   
For reference, here's a list of all STDs: https://www.rfc-editor.org/in-notes/std-ref.txt

**Comment by rjsparks** [comment]
also derivable from https://www.rfc-editor.org/rfc-index.txt and https://www.rfc-editor.org/rfc-index.xml

**Comment by strogonoff** [comment]
Thank you for reporting!

Filed corresponding error against the bibliographic data source compilation. Apparently, at some point the formatting of bibliographic item identifiers was adjusted, but the same was not done with relations (which are expected to use the exact same identifier format).

This left the service unable to resolve relations from `rfcsubseries` to respective RFCs, which is necessary to resolve titles (leaving BibXML serializer no choice but to [substitute `[title unavailable]`](https://bib.ietf.org/public/rfc/bibxml9/reference.STD.0005.xml) in resulting XML, as the `<title>` element cannot be omitted).

I’m following up on this…

**Comment by rjsparks** [comment]
@strogonoff - this is _not_ fixed.
Can you help us understand why?
See https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.STD.0080.xml
(cc @cabo)

**Comment by ronaldtse** [comment]
Sorry about this @rjsparks -- @strogonoff @stefanomunarini @andrew2net please help investigate, thanks.

**Comment by strogonoff** [comment]
When was the source indexed last? I don’t have access to the management panel.

**Comment by strogonoff** [comment]
Source data issue _was_ in fact fixed (by updating relations) and confirmed. The data looked this way (it may still work on staging instance, which doesn’t have auto source reindexing: https://dev.bibxml.org/public/rfc/bibxml-rfcsubseries/reference.STD.0080.xml)

<img width="1246" alt="Screenshot 2022-08-30 at 3 27 10 PM" src="https://user-images.githubusercontent.com/292959/187389232-deab89bb-5bc0-4174-a478-55e73f823ebe.png">

Now we have the same symptom, but it’s a manifestation of a different issue: a consequence of invalid name format prevented the related RFC item from being read and its title extracted (same as described in https://github.com/ietf-tools/bibxml-service/issues/277#issuecomment-1231324302, validation issues for RFC 0020 are available [here](https://bib.ietf.org/indexed-sources/relaton-data-rfcs/RFC0020/), should be fixed today).

**Comment by strogonoff** [comment]
Addressed by the latest PR: https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.STD.0080.xml

**Comment by ronaldtse** [comment]
Yes confirm that this is working and functional. Thanks @strogonoff !

https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.STD.0080.xml
<img width="659" alt="Screen Shot 2022-08-31 at 4 09 32 PM" src="https://user-images.githubusercontent.com/11865/187627151-b75288e8-24a1-4444-8817-873d3f818637.png">
