### ISSUE TITLE
Front page: hover on "Advanced search" button should change cursor into button style

### ISSUE THREAD

**Issue by ronaldtse** [ietf-tools/bibxml-service#254]
Right now hovering on the "Advanced search" button does not show the "click" style cursor, which means that users are not hinted that it is a button to be clicked upon.

<img width="1045" alt="Screen Shot 2022-08-05 at 10 35 16 AM" src="https://user-images.githubusercontent.com/11865/182989582-d79b8ea9-ae5e-424c-ac3f-4c0332326673.png">

This issue is reported by @kesara .

**Comment by kesara** [comment]
Fixed in `v2022.8.8_1`
