### ISSUE TITLE
Provide start time flag to disable all authentication

### ISSUE THREAD

**Issue by ronaldtse** [ietf-tools/bibxml-service#255]
In today's call with @kesara it was communicated that IETF wishes to add an additional feature to the service where Datatracker authentication is disabled and the hints to authenticate are all hidden.

This involves the:
* disabling of OIDC authentication
* disabling the login guards
* hiding text that relate to login and authentication

**Comment by kesara** [comment]
Deployed with `v2022.8.9_1`.
