### ISSUE TITLE
bibxml-rfcsubseries has RFC

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#260]
### Describe the issue

Following URLs with RFC references should generate a `404` response because `bibxml-rfcsubseries` is for STD, BCP and FYI.

* https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.RFC.1737.xml
* https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.RFC.9000.xml

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Specifically, the RFC series is not itself a subseries.

**Comment by ronaldtse** [comment]
Ping @strogonoff @stefanomunarini
