### ISSUE TITLE
bibxml7: non-ASCII found in XML elements that should not contain it

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#261]
### Describe the issue

Non-ASCII is allowed only in a strict subset of XML elements (See https://authors.ietf.org/en/non-ascii-characters-in-rfcxml). However, non-ASCII content (i.e., the dash and apostrophe) appears in `<refcontent>` in the following: 
https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.1007/3-540-46766-1_14.xml

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment]
Thank you @ajeanmahoney for raising this.

DOI CrossRef data allows Unicode, so in order to achieve the strict subset of XML elements, the BibXML Service will be required to "normalize" or "strip" non-compliant characters.

According to your link, these elements can contain Unicode directly:
* `<author>`, `<contact>`, `<organization>`,  `<street>`, `<city>`, `<region>`, `<city>`, `<country>` and `<email>`

However, `<refcontent>` does not support Unicode.

There are two ways to handle this.

@ajeanmahoney any thoughts?

## Wrapping with `<u>` element

According to the link:
> Other than in the resricted elements, non-ASCII characters must be wrapped by the [`<u>`](https://authors.ietf.org/rfcxml-vocabulary#u) element with the format attribute specifying how it is represented.

## Sanitization of symbols

We could implement a sanitization mapping for converting Unicode characters to their equivalents in ASCII, e.g. :

```yaml
"—": "-"
"’": "'"
...
```

**Comment by rjsparks** [comment]
Sanitizing symbols will probably address the issue, and as I understand it, it reflects what the RPC has done internally to date anyhow.

Wrapping with <u> will introduce a new kind of problem and is not a path we should pursue.

**Comment by ajeanmahoney** [comment]
Yes, the RPC converts Unicode characters to their ASCII equivalents when cleaning up bibliographic info.

**Comment by ronaldtse** [comment]
Thanks @ajeanmahoney @rjsparks !

@ajeanmahoney is there an existing mapping that the RPC uses that we can adopt in order to minimize compatibility issues?

**Comment by ajeanmahoney** [comment]
We don't have a formal mapping list or a script that automatically makes updates. We do run a script that highlights where non-ASCII is used in files. The non-ASCII characters that come up frequently in bibliographic entries are the following (and how we replace them):

- smart apostrophe (ASCII apostrophe)
- smart quotes (ASCII double quotes)
- em dash (ASCII hyphen)
- en dash (ASCII hyphen)

**Comment by rjsparks** [comment]
Please skim https://github.com/ietf-tools/xml2rfc/blob/3d7e63462ea05b24c1a0d85a8edf1c4d9b8b4a3a/xml2rfc/util/unicode.py#L202

**Comment by ronaldtse** [comment]
@strogonoff @stefanomunarini can we incorporate [unicode.py](https://github.com/ietf-tools/xml2rfc/blob/3d7e63462ea05b24c1a0d85a8edf1c4d9b8b4a3a/xml2rfc/util/unicode.py) in bibxml-service for ASCII sanitization of BibXML output?

**Comment by strogonoff** [comment]
Since this appears to be logic to reuse, rather than copying the code around it could make sense to take the module, analyze its API and extract it into a PyPI package, maintained separately, which BibXML serializer for Relaton (and probably other bibxml-related packages) could depend on🤔

**Comment by strogonoff** [comment]
Oh, I see it already is a package. Relaton-py should use it, probably🤔

**Comment by samans** [comment]
I came across a new IEEE reference (https://bib.ietf.org/public/rfc/bibxml6/reference.R.IEEE.802.1Q-2022.xml)
That includes this...
<seriesInfo name="IEEE" value="802-1q®-2022"/>

Which contains the "registered trademark" symbol.
When I run idnits I get a warning.

Is that covered under this same "non-ascii" issue?  Or should this be a replacement to something like (R)?

**Comment by ronaldtse** [comment]
@samans thanks for raising the issue. The trademark symbol probably should not occur in the `seriesInfo` element in this context.

Officially, IEEE SA (according to the IEEE SA Style Manual) requests that all their citations add either a `(R)` (registered trademark) or `TM` (trademark) symbol after the document identifier (without edition) on the first display.

However, in this case since it is likely not necessary to encode the symbol inside the `seriesInfo` element.

Pinging @strogonoff @stefanomunarini on this.

**Comment by samans** [comment]
> @samans thanks for raising the issue. The trademark symbol probably should not occur in the `seriesInfo` element in this context.
> 
> Officially, IEEE SA (according to the IEEE SA Style Manual) requests that all their citations add either a `(R)` (registered trademark) or `TM` (trademark) symbol after the document identifier (without edition) on the first display.
> 
> However, in this case since it is likely not necessary to encode the symbol inside the `seriesInfo` element.
> 
> Pinging @strogonoff @stefanomunarini on this.

Thanks for the information.  I know the IEEE is picky about this stuff.  I have let the IETF's IEEE liaison person (Russ Housley) know.

**Comment by rjsparks** [comment]
To be clear - is this ® coming from IEEE source material, or is it something being added along the way?

**Comment by samans** [comment]
I don’t know.  It is in the xml file.  I don’t know how that is generated.

**Comment by stefanomunarini** [comment]
I see there are three different source data files used by the bibxml-service that contain the `®` symbol. Shall this be replaced by `(R)` by the Relaton serializer? Or shall this be updated on the data producer?

**Comment by rjsparks** [comment]
I don't think we want _either_ appearing in the target slugs we are generating for the bibxml service. These are identifiers in our own namespace.

**Comment by russhousley** [comment]
Agree that the target slugs should be ASCII strings, and I do not think that the (R) should not be part of the slug.  It seems straightforward for the downcode routine to be used at the time the bibxml entry is created to ensure the refcontent is all ASCII.

**Comment by rjsparks** [comment]
@stefanomunarini , @ronaldtse Bump?

**Comment by stefanomunarini** [comment]
@rjsparks we are discussing internally whether we should remove the Registered (®) symbol on data producer level or on serialisation level. 

For this purpose, maybe you could help clarify one aspect:
- https://github.com/ietf-tools/relaton-data-ieee/blob/4066f4f9cff9ee4c2f6ec94f47e9599b9d4b08ae/data/IEEE_802.1Q-2003.yaml#L17 contains the Registered symbol as part of the id amongst the docids for that document. Do you want this ® symbol at all here, or can it be dropped?

It seems like the symbol was introduced intentionally https://github.com/relaton/relaton-ieee/issues/21#issuecomment-1171848086 , as reported by @andrew2net

**Comment by ronaldtse** [comment]
Very sorry for the lack of response on my part. I believe we should remove the (R) and (TM) symbols from the BibXML data. The burden of including those symbols on first cite would then be placed on xml2rfc's output.

@rjsparks please let me know if that is an acceptable outcome.

**Comment by ronaldtse** [comment]
@stefanomunarini I believe these symbols are presentational concerns that cannot easily come to a single correct solution.

In Relaton for IEEE, we deal with this by giving two identifiers per IEEE bibliographic item (one without the (TM)/(R) symbol; one with the symbol). However, it is ultimately up to the consumer to chose what to display. And here the consumer is xml2rfc.

We can provide xml2rfc with that option (as in via BibXML) but I don't know if it is the solution that the community would care about.

In any case, it is an IEEE requirement -- for people who cite their standards, they must apply the (TM) or (R) symbol on first use within their content. This is because of trademark laws -- if the trademark is not enforced, it is possible that it counts as non-enforcement. Whether IETF / the RFC community wishes to abide to it, or how to comply with this rule, is not our decision.

**Comment by samans** [comment]
I don't mind the (TM) and (R) in the bib, what I'm reacting to is the non-ascii versions of the trademark and copyright symbol.  The IEEE is ok with (TM) and (R) which work, I just don't know how to get the text in the .xml file changed to remove the non-ascii character and replace it with the ascii-alternative version.  I can simply change it in my generated xml before submitting, but it would be easier if the .xml file in the bibxml area was modified.

**Comment by rjsparks** [comment]
The xml produced at bib.ietf.org should have the value parameter ascii-downcoded as Russ suggests above.
Also @ronaldtse, why are there two `name=IEEE` seriesinfo lines below for `https://bib.ietf.org/public/rfc/bibxml6/reference.R.IEEE.802.1Q-2022.xml` ?
```<reference anchor="IEEE_802.1Q_2022" target="https://ieeexplore.ieee.org/document/10004498">
  <front>
    <title>IEEE Standard for Local and Metropolitan Area Networks--Bridges and Bridged Networks</title>
    <author>
      <organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>
      <address>
        <postal>
          <country>USA</country>
          <city>New York</city>
        </postal>
        <uri>http://www.ieee.org</uri>
      </address>
    </author>
    <date day="30" month="December" year="2022"/>
    <abstract>
      <t>This standard specifies how the Media Access Control (MAC) Service is supported by Bridged Networks, the principles of operation of those networks, and the operation of MAC Bridges and VLAN Bridges, including management, protocols, and algorithms.</t>
    </abstract>
  </front>
  <seriesInfo name="IEEE" value="802-1q-2022"/>
  <seriesInfo name="IEEE" value="802-1q®-2022"/>
  <seriesInfo name="DOI" value="10.1109/IEEESTD.2022.10004498"/>
  <format target="https://ieeexplore.ieee.org/document/10004498" type="TXT"/>
</reference>
```

**Comment by rjsparks** [comment]
To be explicit, I think this would be an ok result:
```
  <front>
    <title>IEEE Standard for Local and Metropolitan Area Networks--Bridges and Bridged Networks</title>
    <author>
      <organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>
      <address>
        <postal>
          <country>USA</country>
          <city>New York</city>
        </postal>
        <uri>http://www.ieee.org</uri>
      </address>
    </author>
    <date day="30" month="December" year="2022"/>
    <abstract>
      <t>This standard specifies how the Media Access Control (MAC) Service is supported by Bridged Networks, the principles of operation of those networks, and the operation of MAC Bridges and VLAN Bridges, including management, protocols, and algorithms.</t>
    </abstract>
  </front>
  <seriesInfo name="IEEE" value="802-1q(R)-2022"/>
  <seriesInfo name="DOI" value="10.1109/IEEESTD.2022.10004498"/>
  <format target="https://ieeexplore.ieee.org/document/10004498" type="TXT"/>
</reference>
```

**Comment by ajeanmahoney** [comment]
So I see in https://github.com/ietf-tools/relaton-data-ieee/blob/4066f4f9cff9ee4c2f6ec94f47e9599b9d4b08ae/data/IEEE_802.1Q-2003.yaml#L17 that there are two doc ids - a primary one that does not have any registration marks and a trademark one that does. Can we use the primary?

The Chicago Manual of Style, which the RPC follows, says that "there is no legal requirement to use these symbols, and they should be omitted wherever possible."  (https://www.chicagomanualofstyle.org/book/ed17/part2/ch08/psec153.html, sorry it's paywalled)

FWIW you cannot even retrieve the document with "802-1q®-2022" or "802-1q(R)-2022" via IEEE's search engine https://ieeexplore.ieee.org/Xplore/home.jsp

**Comment by rjsparks** [comment]
That observation changes where I think we should land. For clarity - our desired result is:
```
  <seriesInfo name="IEEE" value="802-1q-2022"/>
```
with no other `<seriesinfo name="IEEE"` present.

If the `q` in question is `Q` at IEEE's source data, could it be preserved as a `Q` here?
