### ISSUE TITLE
Some draft/I-D entries are missing the "day" entry in the <date .../> field

### ISSUE THREAD

**Issue by lbartholomew-rpc** [ietf-tools/bibxml-service#265]
### Describe the issue

For example, <https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.ietf-core-oscore-groupcomm.xml> is missing the "day" entry -- should be "7 March 2022".  Please compare
with the other two draft entries in the .html file and the rfcdiff file.

Please also compare with (for example) <https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.mattsson-cfrg-det-sigs-with-noise.xml>.

Please see the following output files for examples of what the readers will see:

Current behavior:
--------------------
https://www.rfc-editor.org/v3test/rfc9053-xml2rfc.xml
https://www.rfc-editor.org/v3test/rfc9053-xml2rfc.txt
https://www.rfc-editor.org/v3test/rfc9053-xml2rfc.html

bibxml:
-------------------
https://www.rfc-editor.org/v3test/rfc9053-bibtest.xml
https://www.rfc-editor.org/v3test/rfc9053-bibtest.txt
https://www.rfc-editor.org/v3test/rfc9053-bibtest.html

https://www.rfc-editor.org/v3test/rfc9053-xml2rfc-vs-bibtest-rfcdiff.html

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment]
Thank you @lbartholomew-rpc , this seems to be a bug in the Relaton parsing code. The data source is not parsing the "day" correctly:
https://github.com/ietf-tools/relaton-data-ids/blob/main/data/draft-ietf-core-oscore-groupcomm-14.yaml

We will address this tracked in these issues:
* https://github.com/ietf-tools/relaton-data-ids/issues/22
* https://github.com/relaton/relaton-ietf/issues/97

**Comment by ronaldtse** [comment]
FYI @andrew2net @strogonoff

**Comment by lbartholomew-rpc** [comment]
Hi, @ronaldtse / Ronald.  Thank you for the note and info.!

**Comment by ronaldtse** [comment]
This is now fixed, the updated data can be seen here:
https://github.com/ietf-tools/relaton-data-ids/blob/60f22d03571c8eb35ed8e55a1fde993854b5dcac/data/draft-ietf-core-oscore-groupcomm-14.yaml#L24

You're welcome @lbartholomew-rpc !

**Comment by ronaldtse** [comment]
@lbartholomew-rpc please feel free to close this after verifying, thanks!

**Comment by lbartholomew-rpc** [comment]
@ronaldtse  -- verified.  Thank you!

**Comment by ronaldtse** [comment]
Thanks @lbartholomew-rpc !
