### ISSUE TITLE
BibXML validation error for NIST IR 90-4250

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/bibxml-service#300]
From @russhousley:

> https://bib.ietf.org/get-one/by-docid/?doctype=NIST&docid=NIST+IR+90-4250&format=bibxml
> 
> When I tried to download the bibxml file for this reference, I got this error:
> 
> Could not export this item, the error was: Source data for item NIST IR 90-4250 (NIST) didn’t validate (err: 2 validation errors for BibliographicItem contributor -> 0 -> person -> name -> forename value is not a valid list (type=type_error.list) contributor -> 0 -> person -> name -> forename instance of GenericStringValue, tuple or dict expected (type=type_error.dataclass; class_name=GenericStringValue))
> 
> For some reason, it is displaying the information on the webpage, but it cannot construct the file.

**Comment by rjsparks** [comment]
![image](https://user-images.githubusercontent.com/10996692/191349107-4ad53377-70ba-46ce-8ed4-6c78e1f961ad.png)
looks suspicious

**Comment by rjsparks** [comment]
See also https://bib.ietf.org/indexed-sources/relaton-data-nist/NISTIR_90-4250/

**Comment by ronaldtse** [comment]
The source data seems correct:
https://github.com/relaton/relaton-data-nist/blob/main/data/NISTIR_90-4250.yaml

The validation code seems to expect something else:
```
contributor -> 0 -> person -> name -> forename value is not a valid list (type=type_error.list)

contributor -> 0 -> person -> name -> forename instance of GenericStringValue, tuple or dict expected (type=type_error.dataclass; class_name=GenericStringValue))
```

@strogonoff @stefanomunarini can you help investigate? Thanks.

**Comment by stefanomunarini** [comment]
@ronaldtse this is related to https://github.com/relaton/relaton-py/issues/39 . There is already an [open PR](https://github.com/ietf-ribose/bibxml-service/pull/2) tackling this. It should be merged very soon

**Comment by ronaldtse** [comment]
Closing since https://github.com/ietf-ribose/bibxml-service/pull/2 has been merged.

**Comment by russhousley** [comment]
Yes, but down below it correctly lists the first name a Charles.

**Comment by ronaldtse** [comment]
Thanks @russhousley , actually the issue has been fixed on our fork (ietf-ribose/bibxml-service) but not in the current repo. We'll have to PR this change.
