### ISSUE TITLE
`HOST_NAME` environment variable is not documented

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/bibxml-service#308]
### Describe the issue

I believe @kesara renamed `HOST` to `HOST_NAME` and didn’t update documentation in 04ddc96ee31a55f185d86c812b7919cf7ebc1729. This breaks all environments that still specify `HOST`.

Documentation was updated to point out the need to continuously update documentation (e.g., by grepping) when or before making changes.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Ah, sorry about that. I had to use `HOST_NAME` because there were some issues with having `HOST`. I don't remember the issues now.

**Comment by strogonoff** [comment]
OK, no problem with this one, documentation has been updated.On 24 Oct 2022, at 9:15 PM, Kesara Rathnayake ***@***.***> wrote:﻿
Ah, sorry about that. I had to use HOST_NAME because there were some issues with having HOST. I don't remember the issues now.
