### ISSUE TITLE
CodeCov token should be replaced by a ietf-tools token

### ISSUE THREAD

**Issue by stefanomunarini** [ietf-tools/bibxml-service#320]
### Describe the issue

[`tests`](https://github.com/ietf-tools/bibxml-service/actions/workflows/tests.yml) GitHub Action (CI) is currently using a  CODECOV_TOKEN associated to **ietf-ribose** to upload the tests report to the Codecov servers (coverage reports can be found at https://app.codecov.io/gh/ietf-ribose/bibxml-service).

A new token for this organization, **ietf-tools**, should be created and set in this repository settings (see https://docs.codecov.com/docs#step-2-get-the-repository-upload-token for more info).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
I have updated the `CODECOV_TOKEN`.
