### ISSUE TITLE
RFC references should not list "RFC Publisher" as an author organization

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#321]
### Describe the issue

The addition of the following `<author>` information to RFC references is incorrect:

```
<author>
<organization>RFC Publisher</organization>
</author>
```
See, for example, https://bib.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml

Please revert.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@ronaldtse, @strogonoff  Please treat this as urgent.

**Comment by ronaldtse** [comment]
Sorry I just noticed this. We will find a way to fix the versions using https://github.com/ietf-tools/github-action-build-relaton-yaml-source .

Ping @andrew2net @strogonoff @stefanomunarini

**Comment by strogonoff** [comment]
Version pinning solution is ready in https://github.com/ietf-ribose/relaton-data-rfcs, preparing a PR now.

**Comment by strogonoff** [comment]
@ronaldtse Correction, this is not applicable to the problem of pinning. Pinning by minor version ensures no change in schema occurs (between patch versions), but it makes no guarantees about unchanging data. With current architecture I don’t see what to do except wait for Andrew to roll back this change. @stefanomunarini any ideas?

**Comment by strogonoff** [comment]
> This was introduced yesterday: [ietf-tools/relaton-data-rfcs@ed4f2a3](https://github.com/ietf-tools/relaton-data-rfcs/commit/ed4f2a3d27e2d3baa0b7417ebc327252232033ea)
> 
> I assume that pinning the Relaton gem version in GHAs can avoid issues like this. So, it might be better to prioritize that work too.

@kesara  Sadly, pinning won’t help. Pinning would ensure we don’t inadvertently move from 1.13.x to 1.14.x, but this change—since it’s not a change in the schema, but a change in data—happened between the patch versions of 1.13.x.

To avoid these changes we’d have to not just pin but also have a lockfile to ensure a fully fixed dependency tree of the tools for generating bibdata, with no changes between GHA runs.

**Comment by kesara** [comment]
IMHO if the gem is going to introduce a new set of data, it should be a *minor* version update, not a *patch*.
Pinning to a minor version only going to work if the Relaton gem release strategy is going not going to change any schema & introduce or remove data with patch releases.

> To avoid these changes we’d have to not just pin but also have a lockfile to ensure a fully fixed dependency tree of the tools for generating bibdata, with no changes between GHA runs.

You are suggesting that we lock the version to an exact release right?
Isn't this going to add more overhead in maintenance?
But to fix this urgent issue, I'm happy to go ahead with that.

**Comment by ronaldtse** [comment]
Sorry for getting back late, this issue has been fixed around 10 days ago.

**Comment by ajeanmahoney** [comment]
@ronaldtse My spot check shows that it is fixed. Thanks!

**Comment by ronaldtse** [comment]
Thank you @ajeanmahoney !

**Comment by sginoza** [comment]
It looks like this issue has reappeared.  While trying to publish last week, I noticed that "RFC Publisher" is now listed as an author for RFCs.  For example, see 

https://www.rfc-editor.org/v3test/rfc9333.html#section-12.1
https://www.rfc-editor.org/v3test/rfc9333.xml

It seems that the http://bib.ietf.org/ files contain the "RFC Publisher" data.  Examples:

 https://bib.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml
 https://bib.ietf.org/public/rfc/bibxml/reference.RFC.5234.xml
 https://bib.ietf.org/public/rfc/bibxml/reference.RFC.9020.xml
