### ISSUE TITLE
broken "format" entry

### ISSUE THREAD

**Issue by reschke** [ietf-tools/bibxml-service#326]
### Describe the issue

See, for example:

~~~
<reference anchor="RFC8288" target="https://www.rfc-editor.org/info/rfc8288">
  <front>
    <title>Web Linking</title>
    <author fullname="M. Nottingham" initials="M." surname="Nottingham"/>
    <author>
      <organization>RFC Publisher</organization>
    </author>
    <date month="October" year="2017"/>
    <abstract>
      <t>This specification defines a model for the relationships between resources on the Web ("links") and the type of those relationships ("link relation types").</t>
      <t>It also defines the serialisation of such links in HTTP headers with the Link header field.</t>
    </abstract>
  </front>
  <seriesInfo name="RFC" value="8288"/>
  <seriesInfo name="DOI" value="10.17487/RFC8288"/>
  <format target="https://www.rfc-editor.org/info/rfc8288" type="TXT"/>
</reference>
~~~

Note the \<format> element; it claims format to be "TXT", but points to the info page.

FWIW, "format" is deprecated in RFC 7997.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment]
Thank you @reschke for raising this. 

> Note the <format> element; it claims format to be "TXT", but points to the info page.
> FWIW, "format" is deprecated in RFC 7997.

This issue has been discussed with @rjsparks during development:
* https://github.com/ietf-tools/bibxml-service/issues/142

And also with the RPC team after deployment:
* https://github.com/ietf-tools/bibxml-service/issues/266

I am not confident that there is a clear answer on what the accepted result is (behavior for I-D and RFCs differ).

**Comment by rjsparks** [comment]
What the links for references to RFCs point to has been debated many times (landing page vs actual text). The current discussions more strongly favor actual text adorned with metadata. But this particular bug belongs to the RPC, not the bibxml service - what the bibxml service provides should match what the RPC data source tells it to provide.

**Comment by ajeanmahoney** [comment]
https://www.rfc-editor.org/rfc-index.xml, which is the data source for the bibxml (RFC) citation library, does not provide contents for the ```<format>``` element that is appearing in the bib data.

**Comment by rjsparks** [comment]
hold for a short discussion (see https://mailarchive.ietf.org/arch/browse/rfc-interest/?q=Is%20there%20any%20issue%20with%20removing%20the%20%60%3Cformat%60%20element%20from%20references%20served%20at%20bib.ietf.org)

**Comment by rjsparks** [comment]
That discussion has timed-out. We will move ahead with not producing the format element. I'll make a change to the source for bibxml-ids at the datatracker. We will need to update everything in the middle.
@ronaldtse, @kesara - what else needs to be touched?

**Comment by ronaldtse** [comment]
@rjsparks thanks, we will need to make the corresponding changes because it affects data processing and validation. Do you have a timeline for when this should happen?

Ping @strogonoff @stefanomunarini @andrew2net -- the `<format>` element is going to be removed.

**Comment by rjsparks** [comment]
At best speed please. I have already committed the fix to the datatracker, but it may not be released until first week of February.

**Comment by stefanomunarini** [comment]
``<format>`` element will be removed from the XML serialiser for all of the datasets. Is this the correct understanding, or is this issue related to a/some specific dataset(s)? @ronaldtse

**Comment by rjsparks** [comment]
All datasets - the <format> element was deprecated for v3 (7991), and it doesn't look like the pushback against that deprecation in https://datatracker.ietf.org/doc/html/draft-levkowetz-xml2rfc-v3-implementation-notes-13#name-in-section-33-format is accepted.

The conversation may eventually be taken back through RSWG, but for now, the format element should never be emitted.
