### ISSUE TITLE
Title missing in BibXML export of `draft-ietf-pce-pcep-ifit` (unversioned)

### ISSUE THREAD

**Issue by ronaldtse** [ietf-tools/bibxml-service#327]
### Describe the issue

In this page: https://bib.ietf.org/get-one/by-docid/?docid=draft-ietf-pce-pcep-ifit&doctype=Internet-Draft&query=ietf-pce-pcep-ifit&query_format=docid_regex&page=1

BibXML leads to this link:
* https://bib.ietf.org/get-one/export/?doctype=Internet-Draft&docid=draft-ietf-pce-pcep-ifit&format=bibxml

The resulting XML misses the title:

```xml
<referencegroup anchor="draft-ietf-pce-pcep-ifit">
  <reference anchor="draft-ietf-pce-pcep-ifit-00">
    <front>
      <title>[title unavailable]</title>
      <author/>
    </front>
    <seriesInfo name="Internet-Draft" value="draft-ietf-pce-pcep-ifit-00"/>
  </reference>
  <reference anchor="draft-ietf-pce-pcep-ifit-01">
    <front>
      <title>[title unavailable]</title>
      <author/>
    </front>
    <seriesInfo name="Internet-Draft" value="draft-ietf-pce-pcep-ifit-01"/>
  </reference>
</referencegroup>
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
https://bib.ietf.org/public/rfc/bibxml-ids/reference.I-D.ietf-pce-pcep-ifit.xml returns a populated title
