### ISSUE TITLE
bibxml-doi (bibxml7): target URL should use https and doi.org

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#332]
### Describe the issue

The International DOI Foundation prefers that "https" and "doi.org" be used for DOI URLs. Please see the following DOI Factsheet: https://www.doi.org/factsheets/DOIProxy.html

Currently bib entries in bibxml-doi (bibxml7) use "http" and "dx.doi.org" in the URL of the target attribute of both the ``<reference>``  and ``<format>`` elements. For example:

https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.1007/3-540-60865-6_43.xml
Current: ``target="http://dx.doi.org/10.1007/3-540-60865-6_43"``
Preferred: ``target="https://doi.org/10.1007/3-540-60865-6_43"``

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajeanmahoney** [comment]
Hi all, is there a status update on this? Thanks!

**Comment by rjsparks** [comment]
@ronaldtse is this something that can be changed?

**Comment by cabo** [comment]
kramdown-rfc is not currently providing target attributes for DOI.
Is this something that should be changed?
(The target should be a link from the DOI.xxx text instead of duplicating the text, which I'm not sure can be expressed.)

**Comment by ronaldtse** [comment]
@ajeanmahoney @rjsparks @cabo apologies for not tracking this sooner. We can certainly update the URLs.

Ping @strogonoff @stefanomunarini @andrew2net to update target URL.

**Comment by rjsparks** [comment]
> The correct solution is to remove the target from the bibxml, as xml2rfc then inserts a correct target.

I disagree - the references should stand alone, and not count on side-effects of processing for semantic content.

**Comment by cabo** [comment]
I don't follow.  Are you talking about references in published RFCXML (I'd agree) or what is served from bibxml (I don't agree)?

**Comment by stefanomunarini** [comment]
We get the value for the `target` attribute from Crossref. The bibxml-service does not manipulate this value whatsoever. @cabo @rjsparks

**Comment by cabo** [comment]
Indeed, when I ask https://doi.org about

```
10.1109/access.2020.3012581
```

I get

``` 
URL: http://dx.doi.org/10.1109/access.2020.3012581
```

doilit simply ignores that value, relying on xml2rfc to fill it in based on doi_base_url, which defaults to `https://doi.org/`.  My recommendation not to supply a target value based on this shady URL value stands.

**Comment by ajeanmahoney** [comment]
> We retrieve the value for the `target` attribute from Crossref. The bibxml-service does not manipulate this value whatsoever.

Sounds like this issue should be opened at Crossref.

**Comment by rjsparks** [comment]
Yes, but we can do the right thing _anyhow_.

@cabo : Yes I meant what is returned from bib.ietf.org, not just what is published in RFCs. The fact that you are having to do target manipulation in your code (or that xml2rfc has to do so) is silly. Sure, that processing code can override whatever the bib service provides, but providing the value _we_ would use is the stronger path to consistency.

What is your argument for leaving it off?

**Comment by cabo** [comment]
My main argument for leaving it off is to keep second-guessing to a single place.
We already have the place in xml2rfc.

**Comment by rjsparks** [comment]
This would relieve xml2rfc or anything else from second guessing - instead it can just use what its given unless its explicitly told to override it from the command line.

**Comment by cabo** [comment]
I prefer to have it in xml2rfc as it seems the reaction times can be lower.
But that is a preferene, please do go ahead and fix it here, too.

**Comment by stefanomunarini** [comment]
@cabo @rjsparks can you confirm the fix should be done in bibxml-service?

**Comment by cabo** [comment]
@stefanomunarini I'm not the person to ask

**Comment by rjsparks** [comment]
Yes, please fix it in the bibxml-service.

**Comment by kesara** [comment]
#359 was reverted.
#361 is addressing this issue.
