### ISSUE TITLE
Resolve how we pin to Relaton dependencies

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/bibxml-service#333]

**Comment by rjsparks** [comment]
TODO: Bring the gist of the email conversation into this issue

**Comment by stefanomunarini** [comment]
An action (see https://github.com/ietf-ribose/relaton-gemfiles-fetcher) has been implemented which allows to download the Gemfiles (Gemfile and Gemfile.lock) with pinned versions of the relaton-* data producers. An effort is in place to integrate this action with the current actions responsible for generating the data for the relaton-data-* repositories. An update will come shortly.

**Comment by stefanomunarini** [comment]
The data producers CI has been updated and now makes use of a reusable action in the relaton/support repository. The update can be seen here https://github.com/relaton/support/issues/4 .

Shortly I will create PRs into ietf-tools relaton-data- * repositories.
