### ISSUE TITLE
bibxml-rfcs: target attribute of the reference element must be explicitly set

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#339]
### Describe the issue

Now that the `<format>` element has been removed from bibxml entries, the target attribute for the `<reference>` element needs to be explicitly set and have the following construction for RFC URLs: ``https://www.rfc-editor.org/info/rfcNNNN``

For example
``
<reference anchor="RFC5882" target="https://www.rfc-editor.org/info/rfc5882">
``

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The fix for this should focus only on bibxml-rfc.

**Comment by ajeanmahoney** [comment]
Although it seems trivial, this issue is blocking the publication of RFCs

**Comment by cabo** [comment]
kramdown-rfc will continue to delete target attributes, which will cause xml2rfc to generate useful links in the renderings used during I-D generation.
Please make sure that we don't make changes that would break this.

**Comment by stefanomunarini** [comment]
This issue was fixed with https://github.com/ietf-tools/bibxml-service/pull/340 . However, there seems to be additional changes requested at #341 . I will close this but feel free to reopen if you think it shouldn't be closed just yet.
