### ISSUE TITLE
bib.ietf.org URLs returning HTTP 429 

### ISSUE THREAD

**Issue by jogu** [ietf-tools/bibxml-service#349]
### Describe the issue

Hi

We (the OpenID Foundation) use xml2rfc in bitbucket pipelines to validate documents compile before they are merged. Within the last few days our pipelines have started failing, e.g. https://bitbucket.org/openid/connect/pipelines/results/89 shows errors like:

```
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.9207.xml"
Error: XInclude processing failed: could not load https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.7591.xml, and no fallback was found, line 1461
Unable to complete processing ./openid-4-verifiable-presentations-1_0-17.xml
````

The root cause seems to be that https://bib.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (for example) is returning a http 429 "Too many requests" error, as shown in this run with debugging enabled for xml2rfc:

https://bitbucket.org/openid/connect/pipelines/results/106

Any advice you have is welcome, and apologies in advance if our pipelines have been causing an issue for your server (we only run less than 20 pipelines at day so hopefully not the case).

Thanks

Joseph

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@jogu, `https://xml2rfc.ietf.org/` has a server redirect to `https://bib.ietf.org/`
Since you got HTTP 429, may the server was under stress. We will investigate the issue.

But if `https://xml2rfc.ietf.org/` URLs continue to fail you can replace them with `https://bib.ietf.org/`.

**Comment by NGPixel** [comment]
We recently added rate limiting rules in front of ietf.org.
I modified the allowlist so that these calls don't get flagged.

Let me know if you still get the errors?

**Comment by jogu** [comment]
Thanks for the prompt fix @NGPixel - I tried an initial run and it looks much better. I'll let the rest of our team know so they can retry their own failing runs. I presume I can close this now.
