### ISSUE TITLE
HTTP 429 when fetching files during build

### ISSUE THREAD

**Issue by jricher** [ietf-tools/bibxml-service#350]
### Describe the issue

Our draft builds on Netlify, and the build log is throwing HTTP 429 errors during build, reminiscent of #349 

The latest failing build log can be seen here:

https://app.netlify.com/sites/gnap-core-protocol-editors-draft/deploys/649354c9459c6a0008fe6807

The build runs to completion with no errors when run locally on my laptop, it's only when run from the cloud service that we see the error.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TonyLHansen** [comment]
429 errors are rate limiting issues. You've made too many net requests with insufficient delay between the requests.

**Comment by rjsparks** [comment]
We get quite a bit of abuse from the netblock you're currently in. But we've tuned the rate limit for that block up to what I'm _guessing_ will allow your build to succeed (by counting the number of references in your doc). We'll monitor to see if that also allows too much traffic from the abusers.

**Comment by jricher** [comment]
@TonyLHansen Yes, I have no control over how quickly the automated build system executes this call. That would be something from either the kramdown-rfc tool or the xml2rfc tool. I personally don't care if it takes a few minutes to build but as far as I'm aware all I can do is tell the host system to run the tools.

@rjsparks thank you - the build worked this time! Unfortunately, I don't run or work at Netlify and have no control or insight into other elements in their system that might be able make the problem less on your end. Going out on a limb, I'm guessing that part of the issue stems from the fact that the Netlify system creates a new temporary docker image with no cache each time it builds -- and I don't have a good solution for addressing that.
