### ISSUE TITLE
Improve Relaton dependency pinning

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#355]
### Description

#333 introduced Relaton dependency pinning for Relaton GHAs.
As discussed in https://github.com/ietf-tools/relaton-data-3gpp/issues/17 dependency pinning can be improved by pinning to major versions of Ruby gems, allowing minor updates and patches to be installed.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stefanomunarini** [comment]
All relaton-data-* repositories need to be updated to only override Gemfile, thus removing Gemfile.lock

**Comment by kesara** [comment]
https://github.com/ietf-tools/relaton-data-rfcs GHA is failing right now because of missing `Gemfile.lock`.

**Comment by stefanomunarini** [comment]
I will update the relaton-data repositories by the end of the day @kesara

**Comment by stefanomunarini** [comment]
All affected relaton-data-* repositories have now a PR pending approval and merge.
