### ISSUE TITLE
sources_sourceindexationoutcome table is growing

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#357]
### Describe the issue

The BibXML service stores the outcome of the indexing tasks in `sources_sourceindexationoutcome` table.
The indexing tasks run multiple times a day so the current table size of this database is over 8GB.

I think this is something that should be logged in the filesystem, rather than stored in the database. This gives us the option to ignore or rotate the logs.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stefanomunarini** [comment]
Hi @kesara , we had a brief internal discussion, and thought that perhaps we could delete old records instead? 

We could, for example, delete records older than a X amount of time at the time a new SourceIndexationOutcome entry is added to the database (thus avoiding the need of implementing a new scheduled job, e.g. a weekly job, responsible for deleting records older than a week time).

How do you see this approach?

We are, of course, open to move logs to the filesystem if a good reason is provided.

**Comment by kesara** [comment]
@stefanomunarini I am happy with that approach.

**Comment by strogonoff** [comment]
@kesara To expand on the reason results are stored in the database by original design, it’s that management GUI (and potentially API) exposes those results. Not sure anyone’s using it, but I did use it for troubleshooting during some phases of development.

It’s feasible that we may want to simplify management GUI to omit that feature, but that could create a problem—if someone is working on the indexation logic and wants to see production outcomes, they might need to nudge you every time or get direct access to logs somehow. If relevant logs would be exposed in an easy to dig up manner (e.g., via Sentry), then I guess we could omit logging indexation process/outcomes to database. But as it is perhaps trimming the table would make more sense.

**Comment by kesara** [comment]
@strogonoff No one is using that user interface for troubleshooting. The only use case right now is monitoring the reindexing statuses. I think it's okay to have it logged without providing web access since the queries around these sorts of issues are rare.

**Comment by stefanomunarini** [comment]
That's a good point @strogonoff . If @kesara can confirm the above approach is still the desired one, I will proceed at its implementation. We can, of course, have a more thoughtful discussion about replacing it with something equivalent, as proposed by Anton above, if needed.
