### ISSUE TITLE
Invalid https URLs

### ISSUE THREAD

**Issue by shollenbeck** [ietf-tools/bibxml-service#363]
### Describe the issue

I've noticed multiple invalid https URLs in a number of bibxml entries after I updated an I-D earlier today. For example:

https://bib.ietf.org/public/rfc/bibxml/reference.RFC.6750.xml

https://bib.ietf.org/public/rfc/bibxml/reference.RFC.7009.xml

Note that the https URLs for the RFC Editor location contain "httpss", not "https". I don't have a complete list, but there are more.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@shollenbeck Thanks for the bug report. This was a bug introduced in the [last release](https://github.com/ietf-tools/bibxml-service/releases/tag/2023.7.31_1).

The change is reverted now and is being deployed now.
Please allow ~3 hours for data reindexed.
