### ISSUE TITLE
DOI bibxml error

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#364]
### Describe the issue

I the error `"Error resolving bibliographic item. Tried methods: auto (DoiAdapter: ): uncategorized issue, fallback (): not indexed"`
when I tried to query:
* https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.1007/3-540-60865-6_43.xml
* https://bib.ietf.org/public/rfc/bibxml-doi/reference.DOI.10.1145/2975159.xml
They are working fine now.

Both work fine now.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
In the logs:

**Comment by kesara** [comment]
Do these types of queries make a GET request to `crossref.org`?

**Comment by stefanomunarini** [comment]
Hi @kesara ,

We retrieve DOI data from Crossref using their API. It looks like their system was down when you tried to make that request. 

Can we close this issue as it's not persisting?

**Comment by kesara** [comment]
@stefanomunarini I'm okay with closing this issue.
Can we provide a more helpful error message for the users?

**Comment by stefanomunarini** [comment]
@kesara caching seems like to me a good solution. We can for sure improve error message for the users. I'll take care of this over the next few weeks
