### ISSUE TITLE
Serve BibXML URLs for RFCs without leading zeros

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#367]
### Describe the issue

At the moment BibXML service only servers RFCs that provide four digits.
For example:
* https://bib.ietf.org/public/rfc/bibxml/reference.RFC.0001.xml
* https://bib.ietf.org/public/rfc/bibxml/reference.RFC.0771.xml

These URLs don't work:
* https://bib.ietf.org/public/rfc/bibxml/reference.RFC.1.xml
* https://bib.ietf.org/public/rfc/bibxml/reference.RFC.771.xml

BibXML Service should serve URLs with RFC number <1000 with and without leading zeros.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment]
Thanks @kesara .

@stefanomunarini @strogonoff could we help with this? Thanks.

**Comment by strogonoff** [comment]
For the record, we had situations previously where we fuzzy-matched paths, so that more than one path would match a document, and it caused comments like [this]( https://github.com/ietf-ribose/bibxml-service/blob/5a069257321652b8acd810e8ff28a89d1a4829d1/xml2rfc_compat/fetchers.py#L28-L42) asking us to 404 paths that do not conform to specific scheme. (However, that concerned I-Ds, not RFCs.)

@kesara or someone can you confirm here the requirement to have multiple `/public/rfc/bibxml/` paths match a single RFC?

**Comment by rjsparks** [comment]
I'll confirm this.

We have a legacy issue with accepting leading 0s filling to 4 digits for RFCs1 through 999. We want the variant without the leading zeros to start working.

When we get to rfc10k (which is not so far away), paths ending in, e.g., RFC.12345.xml must work (once RFC12345 is issued).

Any `%04d`-like formatting in the code should be inspected and carefully walled away to serve the legacy case above.

**Comment by TonyLHansen** [comment]
also look for %4.4d, which some systems use as a synonym for %04d

**Comment by stefanomunarini** [comment]
In this case, if we were to serve https://bib.ietf.org/public/rfc/bibxml/reference.RFC.1.xml , how would the rest of the data look like? Meaning, shall the value of `reference.ancor`, `reference.target` and `seriesInfo.value` be updated to have leading 0s or not? In the latter case, data would look like this:

```xml
<reference anchor="RFC1" target="https://www.rfc-editor.org/info/rfc1">
  <front>
    <title>Host Software</title>
    <author fullname="S. Crocker" initials="S." surname="Crocker"/>
    <date month="April" year="1969"/>
  </front>
  <seriesInfo name="RFC" value="1"/>
  <seriesInfo name="DOI" value="10.17487/RFC0001"/>
</reference>
```

**Comment by rjsparks** [comment]
Yes, what you propose (no leading zeros in the payload) is the right thing to do.

**Comment by rjsparks** [comment]
For now, leading zeros will have to exist for the DOI, but I'll see if the RPC can register DOI without the 0s as well.

**Comment by strogonoff** [comment]
> > comments like [this](https://github.com/ietf-ribose/bibxml-service/blob/5a069257321652b8acd810e8ff28a89d1a4829d1/xml2rfc_compat/fetchers.py#L28-L42)
> 
> Did you mean to point to the code here, or was there a discussion to point to instead?

I must have messed up pasting the link, my bad. There was a comment in another issue discussing 404s on I-Ds (or lack thereof, in that case). I’ll find it again but it’s probably not 100% pertinent to the expectations of RFC API consumers.

**Comment by stefanomunarini** [comment]
> > > comments like [this](https://github.com/ietf-ribose/bibxml-service/blob/5a069257321652b8acd810e8ff28a89d1a4829d1/xml2rfc_compat/fetchers.py#L28-L42)
> > 
> > 
> > Did you mean to point to the code here, or was there a discussion to point to instead?
> 
> I must have messed up pasting the link, my bad. There was a comment in another issue discussing 404s on I-Ds (or lack thereof, in that case). I’ll find it again but it’s probably not 100% pertinent to the expectations of RFC API consumers.

Are you perhaps referring to #268 ? @strogonoff
