### ISSUE TITLE
mypy test failures

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#386]
#385 is causing mypy tests to fail:

              @stefanomunarini This is fails mypy tests: https://github.com/ietf-tools/bibxml-service/actions/runs/7281293648/job/19841520536

_Originally posted by @kesara in https://github.com/ietf-tools/bibxml-service/issues/385#issuecomment-1865212375_

**Comment by stefanomunarini** [comment]
Interesting, the workflow was running successfully for the PR. I will look into this, thanks for reporting @kesara

**Comment by stefanomunarini** [comment]
Can we close this @kesara ?

**Comment by kesara** [comment]
Yes. OBE.
