### ISSUE TITLE
The "Releases" info for the bibxml-service repo doesn't show the most recent release

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#391]
### Describe the issue

Compare the information found on https://github.com/ietf-tools/bibxml-service/releases, which says the latest release is [2022.5.13_1](https://github.com/ietf-tools/bibxml-service/releases/tag/2022.5.13_1), with the release information shown on bib.ietf.org, which says the latest release is 2023.11.3_1. I noticed this while looking at #390. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This is because BibXML has only created tags instead of releases with tags.

**Comment by kesara** [comment]
I have generated GitHub releases based on tags from 2022.5.13_1 onwards.
