### ISSUE TITLE
IANA URLs should be https everywhere

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#444]
### Description

See #417 

With #430 only addressed `https://bib.ietf.org/public/rfc/bibxml?/*` URLs.
There are other paths can get non `https` URLs from the UI.

See https://mailarchive.ietf.org/arch/msg/tools-discuss/SRSaoodGjsmvhLupMsNhbtQIBCY/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajeanmahoney** [comment]
This page says that the IANA ref info comes from their rsync server: 
https://github.com/ietf-tools/bibxml-service/wiki/Data-sources

Maybe an issue needs to be opened with IANA to update in their source data?

**Comment by kesara** [comment]
Yes.
URLs from `https://bib.ietf.org/public/rfc/bibxml*/` already do various modifications to comply with the RFC style guide.
But Download buttons from UI provides data from relaton sources directly.
As proposed in #445 should prevent any confusion with different variations.

**Comment by kesara** [comment]
Closing this as OBE.
#447 re-routes BibXML download button content to `xml2rfc` compatible URL.
