### ISSUE TITLE
Performance & error monitoring tools to integrate with in production operation

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/bibxml-service#84]
Which systems does IETF use for monitoring production Django services?

At the moment, BibXML service allows integration with Sentry. Sentry is open-source, started as Django-native and integration with it is painless. In case IETF isn’t using Sentry yet, I’ll note that it can be easily self-hosted for internal monitoring purposes (they maintain a Docker Compose configuration).

If there is another service that IETF already uses (e.g., Prometheus, etc.), we could look into their Python SDKs and push (or expose for pull) relevant metrics from BibXML service.

**Comment by stefanomunarini** [comment]
Unpinned by mistake.

**Comment by kesara** [comment]
I have set up sentry for bibxml-service.
